config/routes.rb
Sweeta::Application.routes.draw do |map|
  resources :users

  resources :sweets

end

app/models/sweet.rb
class Sweet < ActiveRecord::Base
  belongs_to :user

  scope :recent, :order => 'created_at DESC', :limit => 20
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :sweets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  layout 'application'
end

app/controllers/sweets_controller.rb
class SweetsController < ApplicationController
  # GET /sweets
  # GET /sweets.xml
  def index
    @sweets = Sweet.recent

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @sweets }
    end
  end

  # GET /sweets/new
  # GET /sweets/new.xml
  def new
    @sweet = Sweet.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @sweet }
    end
  end

  # POST /sweets
  # POST /sweets.xml
  def create
    @sweet = Sweet.new(params[:sweet])

    respond_to do |format|
      if @sweet.save
        format.html { redirect_to(:sweets, :notice => 'Sweet was successfully created.') }
        format.xml  { render :xml => @sweet, :status => :created, :location => @sweet }
        format.js
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @sweet.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /sweets/1
  # PUT /sweets/1.xml
  def update
    @sweet = Sweet.find(params[:id])

    respond_to do |format|
      if @sweet.update_attributes(params[:sweet])
        format.html { redirect_to(@sweet, :notice => 'Sweet was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @sweet.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /sweets/1
  # DELETE /sweets/1.xml
  def destroy
    @sweet = Sweet.find(params[:id])
    @sweet.destroy

    respond_to do |format|
      format.html { redirect_to(sweets_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.xml
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/new
  # GET /users/new.xml
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.xml
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to(@user, :notice => 'User was successfully created.') }
        format.xml  { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sweets_helper.rb
module SweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sweeta</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/sweets/_form.html.erb
<%= form_for(@sweet) do |f| %>
  <% if @sweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sweet.errors.count, "error") %> prohibited this sweet from being saved:</h2>

      <ul>
      <% @sweet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.collection_select :user_id, User.all, :id, :name %>
  </div>


  <div class="field">
    <%= f.label :text %><br />
    <%= f.text_area :text %>
  </div>
  <div class="field">
    <%= f.label :from %><br />
    <%= f.text_field :from %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sweets/_sweet.html.erb
  <p>
    <strong><%= sweet.user.name %></strong><br/>
    <%= sweet.text %><br/>
    <i>From: <%= sweet.from %></i>
  </p>
  <%= link_to 'Destroy', sweet, :confirm => 'Are you sure?', :method => :delete %>
  <hr/>

app/views/sweets/edit.html.erb
<h1>Editing sweet</h1>

<%= render 'form' %>

<%= link_to 'Show', @sweet %> |
<%= link_to 'Back', sweets_path %>

app/views/sweets/index.html.erb
<h1>Recent sweets</h1>

<% form_for(Sweet.new(:user_id => User.first.id, :from => 'Web'), :remote => true) do |f| %>
  <%= f.text_area :text %><br />
  <%= f.hidden_field :user_id %><br />
  <%= f.hidden_field :from %><br />
  <%= f.submit 'Sweet it' %>
<% end %>

<hr/>

<div id="sweets">
<% @sweets.each do |sweet| %>
  <%= render :partial => 'sweet', :locals => { :sweet => sweet } %>
<% end %>
</div>

<br />

<%= link_to 'New Sweet', new_sweet_path %>

app/views/sweets/new.html.erb
<h1>New sweet</h1>

<%= render 'form' %>

<%= link_to 'Back', sweets_path %>

app/views/sweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Text:</b>
  <%= @sweet.text %>
</p>

<p>
  <b>From:</b>
  <%= @sweet.from %>
</p>


<%= link_to 'Edit', edit_sweet_path(@sweet) %> |
<%= link_to 'Back', sweets_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>